steps:
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'blog'
    - 'gs://${_GCS_BUCKET}/blog'
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'drupal'
    - 'gs://${_GCS_BUCKET}/drupal'
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'wp'
    - 'gs://${_GCS_BUCKET}/wp'
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'setmeta'
    - '-r'
    - '-h'
    - 'cache-control: max-age=86400,public'
    - 'gs://${_GCS_BUCKET}/*'
options:
  logging: CLOUD_LOGGING_ONLY
